[package]
name = "custom_hashmap"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.8.1"


[[bench]]
name = "std_hashmap_my_hashmap"
harness = false

[profile.test]
inherits = "release"
